{
 "title": "Conductor New Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Running Workflows",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "workflow_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "In Progress System Tasks",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "task_in_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Task Queue Depths",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "task_queue_depth", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Task Poll Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "task_poll_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Execution Times For Tasks(Second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "task_execution_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Execution Times For Workflows (Second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    { "expr": "workflow_execution_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Waitings In The Queues For The Tasks (Second)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "task_queue_wait_seconds_sum", "legendFormat": "__auto" }
   ]
  }
 ]
}